[metadata]
  name = 'simple_tcp_ping'
  author = ""

[global]
  plan = "simple_tcp_ping"
  case = "simple_tcp_ping"
  total_instances = 0
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "a"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.build_config]
    enabled = true
    [groups.build_config.build_args]
      SDK_GIT_REF = '{{ or $.Env.SdkGitRef "master" }}'
  [groups.build]
  [groups.run]
    artifact = ""
